#!/usr/bin/env python3
"""Render the engine's Delaunay/Voronoi JSON exports as a portfolio SVG figure.

This script only DRAWS the geometry exported by the C++ engine
(portfolio_export_driver). It performs no geometric computation beyond
mapping coordinates to pixels and clipping finished segments to the viewport.

Usage:
    python3 scripts/render_portfolio_figure.py \
        --delaunay artifacts/portfolio-delaunay-export.json \
        --voronoi artifacts/portfolio-voronoi-export.json \
        --out media/portfolio-figure.svg \
        --seed 42 --command "<command used to produce the exports>"
"""

import argparse
import json
import math
import os

CANVAS = 1400.0          # SVG width and height in px
MARGIN = 30.0            # px of breathing room around the site domain
BACKGROUND = "#FBFCFD"
DELAUNAY_STROKE = "#CDC8BA"
DELAUNAY_WIDTH = 1.1
VORONOI_STROKE = "#1B1B17"
VORONOI_WIDTH = 1.6
SITE_FILL = "#3C5A49"
SITE_RADIUS = 3.5
SITE_HALO = "#FBFCFD"
SITE_HALO_WIDTH = 2.0


def load_json(path):
    with open(path) as handle:
        return json.load(handle)


def make_transform(sites):
    xs = [p[0] for p in sites]
    ys = [p[1] for p in sites]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    span = max(max_x - min_x, max_y - min_y)
    scale = (CANVAS - 2.0 * MARGIN) / span

    def transform(x, y):
        # Flip y so the figure reads in conventional screen orientation.
        px = MARGIN + (x - min_x) * scale
        py = CANVAS - MARGIN - (y - min_y) * scale
        return px, py

    return transform


def clip_segment(x1, y1, x2, y2):
    """Liang-Barsky clip of a finite segment to the canvas rectangle.

    Returns clipped endpoints, or None if the segment lies outside.
    """
    t0, t1 = 0.0, 1.0
    dx, dy = x2 - x1, y2 - y1
    for p, q in ((-dx, x1), (dx, CANVAS - x1), (-dy, y1), (dy, CANVAS - y1)):
        if p == 0.0:
            if q < 0.0:
                return None
            continue
        r = q / p
        if p < 0.0:
            if r > t1:
                return None
            t0 = max(t0, r)
        else:
            if r < t0:
                return None
            t1 = min(t1, r)
    return (x1 + t0 * dx, y1 + t0 * dy, x1 + t1 * dx, y1 + t1 * dy)


def fmt(value):
    return f"{value:.2f}"


def delaunay_edge_set(triangles):
    edges = set()
    for a, b, c in triangles:
        for i, j in ((a, b), (b, c), (c, a)):
            edges.add((min(i, j), max(i, j)))
    return sorted(edges)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--delaunay", required=True)
    parser.add_argument("--voronoi", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--seed", required=True)
    parser.add_argument("--command", required=True,
                        help="exact engine command, recorded in the SVG comment")
    parser.add_argument("--layers", default="overlay",
                        choices=("overlay", "delaunay", "voronoi"),
                        help="draw both layers, or one layer by itself")
    args = parser.parse_args()

    delaunay = load_json(args.delaunay)
    voronoi = load_json(args.voronoi)

    sites = delaunay["sites"]
    triangles = delaunay["triangles"]
    for tri in triangles:
        for index in tri:
            if not 0 <= index < len(sites):
                raise SystemExit(f"triangle index {index} out of range")
    for point in sites + voronoi["vertices"]:
        if not (math.isfinite(point[0]) and math.isfinite(point[1])):
            raise SystemExit("non-finite coordinate in export")

    transform = make_transform(sites)

    lines = []
    lines.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS:.0f}" '
        f'height="{CANVAS:.0f}" viewBox="0 0 {CANVAS:.0f} {CANVAS:.0f}">'
    )
    # XML comments may not contain "--", so hyphen pairs in the command are
    # written as "&#45;&#45;"; the <desc> below carries the raw exact command.
    safe_command = args.command.replace("--", "&#45;&#45;")
    lines.append(f"<!-- seed: {args.seed}; layers: {args.layers} -->")
    lines.append(f"<!-- generated by: {safe_command} (&#45; is an escaped '-') -->")
    lines.append("<!-- Delaunay triangulation and Voronoi diagram computed by "
                 "this repo's C++ engine; this script only renders. -->")
    escaped_command = (args.command.replace("&", "&amp;").replace("<", "&lt;"))
    lines.append(f"<desc>seed {args.seed}; generated by: {escaped_command}</desc>")
    lines.append('<defs><clipPath id="viewport">'
                 f'<rect x="0" y="0" width="{CANVAS:.0f}" height="{CANVAS:.0f}"/>'
                 "</clipPath></defs>")
    lines.append(f'<rect width="{CANVAS:.0f}" height="{CANVAS:.0f}" fill="{BACKGROUND}"/>')
    lines.append('<g clip-path="url(#viewport)">')

    delaunay_edges = delaunay_edge_set(triangles)
    if args.layers in ("overlay", "delaunay"):
        # Solo Delaunay gets the ink treatment; as an underlayer it stays faint.
        if args.layers == "delaunay":
            stroke, width = VORONOI_STROKE, VORONOI_WIDTH
        else:
            stroke, width = DELAUNAY_STROKE, DELAUNAY_WIDTH
        lines.append(f'<g stroke="{stroke}" stroke-width="{width}" fill="none">')
        for i, j in delaunay_edges:
            x1, y1 = transform(*sites[i])
            x2, y2 = transform(*sites[j])
            lines.append(f'<line x1="{fmt(x1)}" y1="{fmt(y1)}" x2="{fmt(x2)}" y2="{fmt(y2)}"/>')
        lines.append("</g>")

    vertices = voronoi["vertices"]
    drawn = 0
    skipped = 0
    if args.layers in ("overlay", "voronoi"):
        lines.append(f'<g stroke="{VORONOI_STROKE}" stroke-width="{VORONOI_WIDTH}" '
                     'stroke-linecap="round" fill="none">')
        for edge in voronoi["edges"]:
            i, j = edge["vertices"]
            if not (0 <= i < len(vertices) and 0 <= j < len(vertices)):
                skipped += 1
                continue
            x1, y1 = transform(*vertices[i])
            x2, y2 = transform(*vertices[j])
            clipped = clip_segment(x1, y1, x2, y2)
            if clipped is None:
                skipped += 1
                continue
            cx1, cy1, cx2, cy2 = clipped
            lines.append(f'<line x1="{fmt(cx1)}" y1="{fmt(cy1)}" x2="{fmt(cx2)}" y2="{fmt(cy2)}"/>')
            drawn += 1
        lines.append("</g>")

    lines.append(f'<g fill="{SITE_FILL}" stroke="{SITE_HALO}" stroke-width="{SITE_HALO_WIDTH}">')
    for x, y in sites:
        px, py = transform(x, y)
        lines.append(f'<circle cx="{fmt(px)}" cy="{fmt(py)}" r="{SITE_RADIUS}"/>')
    lines.append("</g>")

    lines.append("</g>")
    lines.append("</svg>")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as handle:
        handle.write("\n".join(lines) + "\n")

    print(f"layers: {args.layers}")
    print(f"sites: {len(sites)}")
    if args.layers in ("overlay", "delaunay"):
        print(f"delaunay triangles: {len(triangles)}")
        print(f"delaunay edges drawn: {len(delaunay_edges)}")
    if args.layers in ("overlay", "voronoi"):
        print(f"voronoi edges drawn: {drawn}, skipped: {skipped} of {len(voronoi['edges'])}")
    print(f"wrote {args.out} ({os.path.getsize(args.out)} bytes)")


if __name__ == "__main__":
    main()
